# CMake generated Testfile for 
# Source directory: C:/Users/Gilles Colling/Documents/dev/tdc
# Build directory: C:/Users/Gilles Colling/Documents/dev/tdc/build_release
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(smoke "C:/Users/Gilles Colling/Documents/dev/tdc/build_release/Debug/tdc_smoke.exe")
  set_tests_properties(smoke PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Gilles Colling/Documents/dev/tdc/CMakeLists.txt;89;add_test;C:/Users/Gilles Colling/Documents/dev/tdc/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(smoke "C:/Users/Gilles Colling/Documents/dev/tdc/build_release/Release/tdc_smoke.exe")
  set_tests_properties(smoke PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Gilles Colling/Documents/dev/tdc/CMakeLists.txt;89;add_test;C:/Users/Gilles Colling/Documents/dev/tdc/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(smoke "C:/Users/Gilles Colling/Documents/dev/tdc/build_release/MinSizeRel/tdc_smoke.exe")
  set_tests_properties(smoke PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Gilles Colling/Documents/dev/tdc/CMakeLists.txt;89;add_test;C:/Users/Gilles Colling/Documents/dev/tdc/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(smoke "C:/Users/Gilles Colling/Documents/dev/tdc/build_release/RelWithDebInfo/tdc_smoke.exe")
  set_tests_properties(smoke PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Gilles Colling/Documents/dev/tdc/CMakeLists.txt;89;add_test;C:/Users/Gilles Colling/Documents/dev/tdc/CMakeLists.txt;0;")
else()
  add_test(smoke NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(lz2_roundtrip "C:/Users/Gilles Colling/Documents/dev/tdc/build_release/Debug/test_lz2_roundtrip.exe")
  set_tests_properties(lz2_roundtrip PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Gilles Colling/Documents/dev/tdc/CMakeLists.txt;93;add_test;C:/Users/Gilles Colling/Documents/dev/tdc/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(lz2_roundtrip "C:/Users/Gilles Colling/Documents/dev/tdc/build_release/Release/test_lz2_roundtrip.exe")
  set_tests_properties(lz2_roundtrip PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Gilles Colling/Documents/dev/tdc/CMakeLists.txt;93;add_test;C:/Users/Gilles Colling/Documents/dev/tdc/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(lz2_roundtrip "C:/Users/Gilles Colling/Documents/dev/tdc/build_release/MinSizeRel/test_lz2_roundtrip.exe")
  set_tests_properties(lz2_roundtrip PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Gilles Colling/Documents/dev/tdc/CMakeLists.txt;93;add_test;C:/Users/Gilles Colling/Documents/dev/tdc/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(lz2_roundtrip "C:/Users/Gilles Colling/Documents/dev/tdc/build_release/RelWithDebInfo/test_lz2_roundtrip.exe")
  set_tests_properties(lz2_roundtrip PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Gilles Colling/Documents/dev/tdc/CMakeLists.txt;93;add_test;C:/Users/Gilles Colling/Documents/dev/tdc/CMakeLists.txt;0;")
else()
  add_test(lz2_roundtrip NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(huffman_roundtrip "C:/Users/Gilles Colling/Documents/dev/tdc/build_release/Debug/test_huffman_roundtrip.exe")
  set_tests_properties(huffman_roundtrip PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Gilles Colling/Documents/dev/tdc/CMakeLists.txt;97;add_test;C:/Users/Gilles Colling/Documents/dev/tdc/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(huffman_roundtrip "C:/Users/Gilles Colling/Documents/dev/tdc/build_release/Release/test_huffman_roundtrip.exe")
  set_tests_properties(huffman_roundtrip PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Gilles Colling/Documents/dev/tdc/CMakeLists.txt;97;add_test;C:/Users/Gilles Colling/Documents/dev/tdc/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(huffman_roundtrip "C:/Users/Gilles Colling/Documents/dev/tdc/build_release/MinSizeRel/test_huffman_roundtrip.exe")
  set_tests_properties(huffman_roundtrip PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Gilles Colling/Documents/dev/tdc/CMakeLists.txt;97;add_test;C:/Users/Gilles Colling/Documents/dev/tdc/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(huffman_roundtrip "C:/Users/Gilles Colling/Documents/dev/tdc/build_release/RelWithDebInfo/test_huffman_roundtrip.exe")
  set_tests_properties(huffman_roundtrip PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Gilles Colling/Documents/dev/tdc/CMakeLists.txt;97;add_test;C:/Users/Gilles Colling/Documents/dev/tdc/CMakeLists.txt;0;")
else()
  add_test(huffman_roundtrip NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(fse_roundtrip "C:/Users/Gilles Colling/Documents/dev/tdc/build_release/Debug/test_fse_roundtrip.exe")
  set_tests_properties(fse_roundtrip PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Gilles Colling/Documents/dev/tdc/CMakeLists.txt;101;add_test;C:/Users/Gilles Colling/Documents/dev/tdc/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(fse_roundtrip "C:/Users/Gilles Colling/Documents/dev/tdc/build_release/Release/test_fse_roundtrip.exe")
  set_tests_properties(fse_roundtrip PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Gilles Colling/Documents/dev/tdc/CMakeLists.txt;101;add_test;C:/Users/Gilles Colling/Documents/dev/tdc/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(fse_roundtrip "C:/Users/Gilles Colling/Documents/dev/tdc/build_release/MinSizeRel/test_fse_roundtrip.exe")
  set_tests_properties(fse_roundtrip PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Gilles Colling/Documents/dev/tdc/CMakeLists.txt;101;add_test;C:/Users/Gilles Colling/Documents/dev/tdc/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(fse_roundtrip "C:/Users/Gilles Colling/Documents/dev/tdc/build_release/RelWithDebInfo/test_fse_roundtrip.exe")
  set_tests_properties(fse_roundtrip PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Gilles Colling/Documents/dev/tdc/CMakeLists.txt;101;add_test;C:/Users/Gilles Colling/Documents/dev/tdc/CMakeLists.txt;0;")
else()
  add_test(fse_roundtrip NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(byte_shuffle_roundtrip "C:/Users/Gilles Colling/Documents/dev/tdc/build_release/Debug/test_byte_shuffle_roundtrip.exe")
  set_tests_properties(byte_shuffle_roundtrip PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Gilles Colling/Documents/dev/tdc/CMakeLists.txt;105;add_test;C:/Users/Gilles Colling/Documents/dev/tdc/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(byte_shuffle_roundtrip "C:/Users/Gilles Colling/Documents/dev/tdc/build_release/Release/test_byte_shuffle_roundtrip.exe")
  set_tests_properties(byte_shuffle_roundtrip PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Gilles Colling/Documents/dev/tdc/CMakeLists.txt;105;add_test;C:/Users/Gilles Colling/Documents/dev/tdc/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(byte_shuffle_roundtrip "C:/Users/Gilles Colling/Documents/dev/tdc/build_release/MinSizeRel/test_byte_shuffle_roundtrip.exe")
  set_tests_properties(byte_shuffle_roundtrip PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Gilles Colling/Documents/dev/tdc/CMakeLists.txt;105;add_test;C:/Users/Gilles Colling/Documents/dev/tdc/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(byte_shuffle_roundtrip "C:/Users/Gilles Colling/Documents/dev/tdc/build_release/RelWithDebInfo/test_byte_shuffle_roundtrip.exe")
  set_tests_properties(byte_shuffle_roundtrip PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Gilles Colling/Documents/dev/tdc/CMakeLists.txt;105;add_test;C:/Users/Gilles Colling/Documents/dev/tdc/CMakeLists.txt;0;")
else()
  add_test(byte_shuffle_roundtrip NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(quantize_roundtrip "C:/Users/Gilles Colling/Documents/dev/tdc/build_release/Debug/test_quantize_roundtrip.exe")
  set_tests_properties(quantize_roundtrip PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Gilles Colling/Documents/dev/tdc/CMakeLists.txt;112;add_test;C:/Users/Gilles Colling/Documents/dev/tdc/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(quantize_roundtrip "C:/Users/Gilles Colling/Documents/dev/tdc/build_release/Release/test_quantize_roundtrip.exe")
  set_tests_properties(quantize_roundtrip PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Gilles Colling/Documents/dev/tdc/CMakeLists.txt;112;add_test;C:/Users/Gilles Colling/Documents/dev/tdc/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(quantize_roundtrip "C:/Users/Gilles Colling/Documents/dev/tdc/build_release/MinSizeRel/test_quantize_roundtrip.exe")
  set_tests_properties(quantize_roundtrip PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Gilles Colling/Documents/dev/tdc/CMakeLists.txt;112;add_test;C:/Users/Gilles Colling/Documents/dev/tdc/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(quantize_roundtrip "C:/Users/Gilles Colling/Documents/dev/tdc/build_release/RelWithDebInfo/test_quantize_roundtrip.exe")
  set_tests_properties(quantize_roundtrip PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Gilles Colling/Documents/dev/tdc/CMakeLists.txt;112;add_test;C:/Users/Gilles Colling/Documents/dev/tdc/CMakeLists.txt;0;")
else()
  add_test(quantize_roundtrip NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(zigzag_roundtrip "C:/Users/Gilles Colling/Documents/dev/tdc/build_release/Debug/test_zigzag_roundtrip.exe")
  set_tests_properties(zigzag_roundtrip PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Gilles Colling/Documents/dev/tdc/CMakeLists.txt;116;add_test;C:/Users/Gilles Colling/Documents/dev/tdc/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(zigzag_roundtrip "C:/Users/Gilles Colling/Documents/dev/tdc/build_release/Release/test_zigzag_roundtrip.exe")
  set_tests_properties(zigzag_roundtrip PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Gilles Colling/Documents/dev/tdc/CMakeLists.txt;116;add_test;C:/Users/Gilles Colling/Documents/dev/tdc/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(zigzag_roundtrip "C:/Users/Gilles Colling/Documents/dev/tdc/build_release/MinSizeRel/test_zigzag_roundtrip.exe")
  set_tests_properties(zigzag_roundtrip PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Gilles Colling/Documents/dev/tdc/CMakeLists.txt;116;add_test;C:/Users/Gilles Colling/Documents/dev/tdc/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(zigzag_roundtrip "C:/Users/Gilles Colling/Documents/dev/tdc/build_release/RelWithDebInfo/test_zigzag_roundtrip.exe")
  set_tests_properties(zigzag_roundtrip PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Gilles Colling/Documents/dev/tdc/CMakeLists.txt;116;add_test;C:/Users/Gilles Colling/Documents/dev/tdc/CMakeLists.txt;0;")
else()
  add_test(zigzag_roundtrip NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(delta1d_roundtrip "C:/Users/Gilles Colling/Documents/dev/tdc/build_release/Debug/test_delta1d_roundtrip.exe")
  set_tests_properties(delta1d_roundtrip PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Gilles Colling/Documents/dev/tdc/CMakeLists.txt;120;add_test;C:/Users/Gilles Colling/Documents/dev/tdc/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(delta1d_roundtrip "C:/Users/Gilles Colling/Documents/dev/tdc/build_release/Release/test_delta1d_roundtrip.exe")
  set_tests_properties(delta1d_roundtrip PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Gilles Colling/Documents/dev/tdc/CMakeLists.txt;120;add_test;C:/Users/Gilles Colling/Documents/dev/tdc/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(delta1d_roundtrip "C:/Users/Gilles Colling/Documents/dev/tdc/build_release/MinSizeRel/test_delta1d_roundtrip.exe")
  set_tests_properties(delta1d_roundtrip PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Gilles Colling/Documents/dev/tdc/CMakeLists.txt;120;add_test;C:/Users/Gilles Colling/Documents/dev/tdc/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(delta1d_roundtrip "C:/Users/Gilles Colling/Documents/dev/tdc/build_release/RelWithDebInfo/test_delta1d_roundtrip.exe")
  set_tests_properties(delta1d_roundtrip PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Gilles Colling/Documents/dev/tdc/CMakeLists.txt;120;add_test;C:/Users/Gilles Colling/Documents/dev/tdc/CMakeLists.txt;0;")
else()
  add_test(delta1d_roundtrip NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(raw_roundtrip "C:/Users/Gilles Colling/Documents/dev/tdc/build_release/Debug/test_raw_roundtrip.exe")
  set_tests_properties(raw_roundtrip PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Gilles Colling/Documents/dev/tdc/CMakeLists.txt;124;add_test;C:/Users/Gilles Colling/Documents/dev/tdc/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(raw_roundtrip "C:/Users/Gilles Colling/Documents/dev/tdc/build_release/Release/test_raw_roundtrip.exe")
  set_tests_properties(raw_roundtrip PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Gilles Colling/Documents/dev/tdc/CMakeLists.txt;124;add_test;C:/Users/Gilles Colling/Documents/dev/tdc/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(raw_roundtrip "C:/Users/Gilles Colling/Documents/dev/tdc/build_release/MinSizeRel/test_raw_roundtrip.exe")
  set_tests_properties(raw_roundtrip PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Gilles Colling/Documents/dev/tdc/CMakeLists.txt;124;add_test;C:/Users/Gilles Colling/Documents/dev/tdc/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(raw_roundtrip "C:/Users/Gilles Colling/Documents/dev/tdc/build_release/RelWithDebInfo/test_raw_roundtrip.exe")
  set_tests_properties(raw_roundtrip PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Gilles Colling/Documents/dev/tdc/CMakeLists.txt;124;add_test;C:/Users/Gilles Colling/Documents/dev/tdc/CMakeLists.txt;0;")
else()
  add_test(raw_roundtrip NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pred2d_roundtrip "C:/Users/Gilles Colling/Documents/dev/tdc/build_release/Debug/test_pred2d_roundtrip.exe")
  set_tests_properties(pred2d_roundtrip PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Gilles Colling/Documents/dev/tdc/CMakeLists.txt;128;add_test;C:/Users/Gilles Colling/Documents/dev/tdc/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pred2d_roundtrip "C:/Users/Gilles Colling/Documents/dev/tdc/build_release/Release/test_pred2d_roundtrip.exe")
  set_tests_properties(pred2d_roundtrip PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Gilles Colling/Documents/dev/tdc/CMakeLists.txt;128;add_test;C:/Users/Gilles Colling/Documents/dev/tdc/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pred2d_roundtrip "C:/Users/Gilles Colling/Documents/dev/tdc/build_release/MinSizeRel/test_pred2d_roundtrip.exe")
  set_tests_properties(pred2d_roundtrip PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Gilles Colling/Documents/dev/tdc/CMakeLists.txt;128;add_test;C:/Users/Gilles Colling/Documents/dev/tdc/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pred2d_roundtrip "C:/Users/Gilles Colling/Documents/dev/tdc/build_release/RelWithDebInfo/test_pred2d_roundtrip.exe")
  set_tests_properties(pred2d_roundtrip PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Gilles Colling/Documents/dev/tdc/CMakeLists.txt;128;add_test;C:/Users/Gilles Colling/Documents/dev/tdc/CMakeLists.txt;0;")
else()
  add_test(pred2d_roundtrip NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pred3d_roundtrip "C:/Users/Gilles Colling/Documents/dev/tdc/build_release/Debug/test_pred3d_roundtrip.exe")
  set_tests_properties(pred3d_roundtrip PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Gilles Colling/Documents/dev/tdc/CMakeLists.txt;132;add_test;C:/Users/Gilles Colling/Documents/dev/tdc/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pred3d_roundtrip "C:/Users/Gilles Colling/Documents/dev/tdc/build_release/Release/test_pred3d_roundtrip.exe")
  set_tests_properties(pred3d_roundtrip PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Gilles Colling/Documents/dev/tdc/CMakeLists.txt;132;add_test;C:/Users/Gilles Colling/Documents/dev/tdc/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pred3d_roundtrip "C:/Users/Gilles Colling/Documents/dev/tdc/build_release/MinSizeRel/test_pred3d_roundtrip.exe")
  set_tests_properties(pred3d_roundtrip PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Gilles Colling/Documents/dev/tdc/CMakeLists.txt;132;add_test;C:/Users/Gilles Colling/Documents/dev/tdc/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pred3d_roundtrip "C:/Users/Gilles Colling/Documents/dev/tdc/build_release/RelWithDebInfo/test_pred3d_roundtrip.exe")
  set_tests_properties(pred3d_roundtrip PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Gilles Colling/Documents/dev/tdc/CMakeLists.txt;132;add_test;C:/Users/Gilles Colling/Documents/dev/tdc/CMakeLists.txt;0;")
else()
  add_test(pred3d_roundtrip NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(dict1d_roundtrip "C:/Users/Gilles Colling/Documents/dev/tdc/build_release/Debug/test_dict1d_roundtrip.exe")
  set_tests_properties(dict1d_roundtrip PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Gilles Colling/Documents/dev/tdc/CMakeLists.txt;136;add_test;C:/Users/Gilles Colling/Documents/dev/tdc/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(dict1d_roundtrip "C:/Users/Gilles Colling/Documents/dev/tdc/build_release/Release/test_dict1d_roundtrip.exe")
  set_tests_properties(dict1d_roundtrip PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Gilles Colling/Documents/dev/tdc/CMakeLists.txt;136;add_test;C:/Users/Gilles Colling/Documents/dev/tdc/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(dict1d_roundtrip "C:/Users/Gilles Colling/Documents/dev/tdc/build_release/MinSizeRel/test_dict1d_roundtrip.exe")
  set_tests_properties(dict1d_roundtrip PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Gilles Colling/Documents/dev/tdc/CMakeLists.txt;136;add_test;C:/Users/Gilles Colling/Documents/dev/tdc/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(dict1d_roundtrip "C:/Users/Gilles Colling/Documents/dev/tdc/build_release/RelWithDebInfo/test_dict1d_roundtrip.exe")
  set_tests_properties(dict1d_roundtrip PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Gilles Colling/Documents/dev/tdc/CMakeLists.txt;136;add_test;C:/Users/Gilles Colling/Documents/dev/tdc/CMakeLists.txt;0;")
else()
  add_test(dict1d_roundtrip NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(pipeline_roundtrip "C:/Users/Gilles Colling/Documents/dev/tdc/build_release/Debug/test_pipeline_roundtrip.exe")
  set_tests_properties(pipeline_roundtrip PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Gilles Colling/Documents/dev/tdc/CMakeLists.txt;140;add_test;C:/Users/Gilles Colling/Documents/dev/tdc/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(pipeline_roundtrip "C:/Users/Gilles Colling/Documents/dev/tdc/build_release/Release/test_pipeline_roundtrip.exe")
  set_tests_properties(pipeline_roundtrip PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Gilles Colling/Documents/dev/tdc/CMakeLists.txt;140;add_test;C:/Users/Gilles Colling/Documents/dev/tdc/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(pipeline_roundtrip "C:/Users/Gilles Colling/Documents/dev/tdc/build_release/MinSizeRel/test_pipeline_roundtrip.exe")
  set_tests_properties(pipeline_roundtrip PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Gilles Colling/Documents/dev/tdc/CMakeLists.txt;140;add_test;C:/Users/Gilles Colling/Documents/dev/tdc/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(pipeline_roundtrip "C:/Users/Gilles Colling/Documents/dev/tdc/build_release/RelWithDebInfo/test_pipeline_roundtrip.exe")
  set_tests_properties(pipeline_roundtrip PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Gilles Colling/Documents/dev/tdc/CMakeLists.txt;140;add_test;C:/Users/Gilles Colling/Documents/dev/tdc/CMakeLists.txt;0;")
else()
  add_test(pipeline_roundtrip NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(format_validate "C:/Users/Gilles Colling/Documents/dev/tdc/build_release/Debug/test_format_validate.exe")
  set_tests_properties(format_validate PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Gilles Colling/Documents/dev/tdc/CMakeLists.txt;144;add_test;C:/Users/Gilles Colling/Documents/dev/tdc/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(format_validate "C:/Users/Gilles Colling/Documents/dev/tdc/build_release/Release/test_format_validate.exe")
  set_tests_properties(format_validate PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Gilles Colling/Documents/dev/tdc/CMakeLists.txt;144;add_test;C:/Users/Gilles Colling/Documents/dev/tdc/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(format_validate "C:/Users/Gilles Colling/Documents/dev/tdc/build_release/MinSizeRel/test_format_validate.exe")
  set_tests_properties(format_validate PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Gilles Colling/Documents/dev/tdc/CMakeLists.txt;144;add_test;C:/Users/Gilles Colling/Documents/dev/tdc/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(format_validate "C:/Users/Gilles Colling/Documents/dev/tdc/build_release/RelWithDebInfo/test_format_validate.exe")
  set_tests_properties(format_validate PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Gilles Colling/Documents/dev/tdc/CMakeLists.txt;144;add_test;C:/Users/Gilles Colling/Documents/dev/tdc/CMakeLists.txt;0;")
else()
  add_test(format_validate NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(bench_smoke "C:/Users/Gilles Colling/Documents/dev/tdc/build_release/Debug/bench_throughput.exe" "--smoke")
  set_tests_properties(bench_smoke PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Gilles Colling/Documents/dev/tdc/CMakeLists.txt;161;add_test;C:/Users/Gilles Colling/Documents/dev/tdc/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(bench_smoke "C:/Users/Gilles Colling/Documents/dev/tdc/build_release/Release/bench_throughput.exe" "--smoke")
  set_tests_properties(bench_smoke PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Gilles Colling/Documents/dev/tdc/CMakeLists.txt;161;add_test;C:/Users/Gilles Colling/Documents/dev/tdc/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(bench_smoke "C:/Users/Gilles Colling/Documents/dev/tdc/build_release/MinSizeRel/bench_throughput.exe" "--smoke")
  set_tests_properties(bench_smoke PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Gilles Colling/Documents/dev/tdc/CMakeLists.txt;161;add_test;C:/Users/Gilles Colling/Documents/dev/tdc/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(bench_smoke "C:/Users/Gilles Colling/Documents/dev/tdc/build_release/RelWithDebInfo/bench_throughput.exe" "--smoke")
  set_tests_properties(bench_smoke PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Gilles Colling/Documents/dev/tdc/CMakeLists.txt;161;add_test;C:/Users/Gilles Colling/Documents/dev/tdc/CMakeLists.txt;0;")
else()
  add_test(bench_smoke NOT_AVAILABLE)
endif()
